import type { Metadata } from "next";
import { Eczar } from "next/font/google";
import "./globals.css";

const eczar = Eczar({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${eczar.className} bg-background text-foreground`}>
        {children}
      </body>
    </html>
  );
}
